In [50]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn import preprocessing
from sklearn import kernel_ridge

Testul de train

In [67]:
train = pd.read_csv('train.csv')
label = train["label"]
X = train.drop(labels=["label"], axis=1)

n = len(label)
number = int(n *80/100)
print(number,n)

33600 42000


In [70]:
xdef = X[:number]
ydef = label[:number]
xtest = X[number:]
ytest = label[number:]
print(ytest)

33600    0
33601    7
33602    7
33603    2
33604    2
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 8400, dtype: int64


In [69]:
model = MultinomialNB()
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

0.8225


In [28]:
model = SVC()
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

0.9772619047619048


In [6]:
xdef =preprocessing.normalize(xdef)
xtest = preprocessing.normalize(xtest)
model = SVC()
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

0.9779761904761904


In [ ]:
model = SVC(kernel='poly')
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

In [8]:
from sklearn.kernel_ridge import KernelRidge
xdef =preprocessing.normalize(xdef)
xtest = preprocessing.normalize(xtest)
model = KernelRidge()
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

0.0


In [66]:
xdef = xdef.sum()
print(xdef)

363777.0937406119


In [74]:
from sklearn.impute import SimpleImputer
from sklearn import neighbors
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(xdef)
xdef = imputer.transform(xdef)
xdef =preprocessing.normalize(xdef)
xtest = preprocessing.normalize(xtest)
n_neighbors = 5
model =  neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
model.fit(xdef, ydef)
test_predictions=model.predict(xtest)
#print(test_predictions)
acc=np.mean(test_predictions==ytest)
print(acc)

0.9748809523809524


predict

In [26]:
train = pd.read_csv('test.csv')
model = MultinomialNB()
model.fit(X, label)
test_predictions=model.predict(train)
print(test_predictions)

result = pd.Series(test_predictions, name="Label")
submission = pd.concat([pd.Series(range(1, 28001), name="ImageId"), result], axis=1)
submission.to_csv("Digit_sub.csv", index=False)


[2 0 9 ... 3 9 2]


In [29]:
train = pd.read_csv('test.csv')
model = SVC()
model.fit(X, label)
test_predictions=model.predict(train)
print(test_predictions)

result = pd.Series(test_predictions, name="Label")
submission = pd.concat([pd.Series(range(1, 28001), name="ImageId"), result], axis=1)
submission.to_csv("Digit_sub.csv", index=False)


[2 0 9 ... 3 9 2]


In [7]:
train = pd.read_csv('test.csv')
model = SVC()

X =preprocessing.normalize(X)
train = preprocessing.normalize(train)

model.fit(X, label)
test_predictions=model.predict(train)
print(test_predictions)

result = pd.Series(test_predictions, name="Label")
submission = pd.concat([pd.Series(range(1, 28001), name="ImageId"), result], axis=1)
submission.to_csv("Digit_sub.csv", index=False)


[2 0 9 ... 3 9 2]
